// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yunloli/aiferry/internal/dao/internal"
)

// apiKeyChannelGroupsDao is the data access object for the table api_key_channel_groups.
// You can define custom methods on it to extend its functionality as needed.
type apiKeyChannelGroupsDao struct {
	*internal.ApiKeyChannelGroupsDao
}

var (
	// ApiKeyChannelGroups is a globally accessible object for table api_key_channel_groups operations.
	ApiKeyChannelGroups = apiKeyChannelGroupsDao{internal.NewApiKeyChannelGroupsDao()}
)

// Add your custom methods and functionality below.
