// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yunloli/aiferry/internal/dao/internal"
)

// apiKeyModelsDao is the data access object for the table api_key_models.
// You can define custom methods on it to extend its functionality as needed.
type apiKeyModelsDao struct {
	*internal.ApiKeyModelsDao
}

var (
	// ApiKeyModels is a globally accessible object for table api_key_models operations.
	ApiKeyModels = apiKeyModelsDao{internal.NewApiKeyModelsDao()}
)

// Add your custom methods and functionality below.
