// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yunloli/aiferry/internal/dao/internal"
)

// apiKeyChannelCredentialsDao is the data access object for the table api_key_channel_credentials.
// You can define custom methods on it to extend its functionality as needed.
type apiKeyChannelCredentialsDao struct {
	*internal.ApiKeyChannelCredentialsDao
}

var (
	// ApiKeyChannelCredentials is a globally accessible object for table api_key_channel_credentials operations.
	ApiKeyChannelCredentials = apiKeyChannelCredentialsDao{internal.NewApiKeyChannelCredentialsDao()}
)

// Add your custom methods and functionality below.
