// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yunloli/aiferry/internal/dao/internal"
)

// channelModelCredentialsDao is the data access object for the table channel_model_credentials.
// You can define custom methods on it to extend its functionality as needed.
type channelModelCredentialsDao struct {
	*internal.ChannelModelCredentialsDao
}

var (
	// ChannelModelCredentials is a globally accessible object for table channel_model_credentials operations.
	ChannelModelCredentials = channelModelCredentialsDao{internal.NewChannelModelCredentialsDao()}
)

// Add your custom methods and functionality below.
