// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yunloli/aiferry/internal/dao/internal"
)

// channelTypesDao is the data access object for the table channel_types.
// You can define custom methods on it to extend its functionality as needed.
type channelTypesDao struct {
	*internal.ChannelTypesDao
}

var (
	// ChannelTypes is a globally accessible object for table channel_types operations.
	ChannelTypes = channelTypesDao{internal.NewChannelTypesDao()}
)

// Add your custom methods and functionality below.
