// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yunloli/aiferry/internal/dao/internal"
)

// channelCredentialsDao is the data access object for the table channel_credentials.
// You can define custom methods on it to extend its functionality as needed.
type channelCredentialsDao struct {
	*internal.ChannelCredentialsDao
}

var (
	// ChannelCredentials is a globally accessible object for table channel_credentials operations.
	ChannelCredentials = channelCredentialsDao{internal.NewChannelCredentialsDao()}
)

// Add your custom methods and functionality below.
