// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yunloli/aiferry/internal/dao/internal"
)

// channelModelsDao is the data access object for the table channel_models.
// You can define custom methods on it to extend its functionality as needed.
type channelModelsDao struct {
	*internal.ChannelModelsDao
}

var (
	// ChannelModels is a globally accessible object for table channel_models operations.
	ChannelModels = channelModelsDao{internal.NewChannelModelsDao()}
)

// Add your custom methods and functionality below.
