// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yunloli/aiferry/internal/dao/internal"
)

// channelGroupsDao is the data access object for the table channel_groups.
// You can define custom methods on it to extend its functionality as needed.
type channelGroupsDao struct {
	*internal.ChannelGroupsDao
}

var (
	// ChannelGroups is a globally accessible object for table channel_groups operations.
	ChannelGroups = channelGroupsDao{internal.NewChannelGroupsDao()}
)

// Add your custom methods and functionality below.
