// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yunloli/aiferry/internal/dao/internal"
)

// channelGroupMembersDao is the data access object for the table channel_group_members.
// You can define custom methods on it to extend its functionality as needed.
type channelGroupMembersDao struct {
	*internal.ChannelGroupMembersDao
}

var (
	// ChannelGroupMembers is a globally accessible object for table channel_group_members operations.
	ChannelGroupMembers = channelGroupMembersDao{internal.NewChannelGroupMembersDao()}
)

// Add your custom methods and functionality below.
