// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yunloli/aiferry/internal/dao/internal"
)

// channelCredentialCostSnapshotsDao is the data access object for the table channel_credential_cost_snapshots.
// You can define custom methods on it to extend its functionality as needed.
type channelCredentialCostSnapshotsDao struct {
	*internal.ChannelCredentialCostSnapshotsDao
}

var (
	// ChannelCredentialCostSnapshots is a globally accessible object for table channel_credential_cost_snapshots operations.
	ChannelCredentialCostSnapshots = channelCredentialCostSnapshotsDao{internal.NewChannelCredentialCostSnapshotsDao()}
)

// Add your custom methods and functionality below.
