// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yunloli/aiferry/internal/dao/internal"
)

// channelCostSnapshotsDao is the data access object for the table channel_cost_snapshots.
// You can define custom methods on it to extend its functionality as needed.
type channelCostSnapshotsDao struct {
	*internal.ChannelCostSnapshotsDao
}

var (
	// ChannelCostSnapshots is a globally accessible object for table channel_cost_snapshots operations.
	ChannelCostSnapshots = channelCostSnapshotsDao{internal.NewChannelCostSnapshotsDao()}
)

// Add your custom methods and functionality below.
