// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yunloli/aiferry/internal/dao/internal"
)

// modelPricesDao is the data access object for the table model_prices.
// You can define custom methods on it to extend its functionality as needed.
type modelPricesDao struct {
	*internal.ModelPricesDao
}

var (
	// ModelPrices is a globally accessible object for table model_prices operations.
	ModelPrices = modelPricesDao{internal.NewModelPricesDao()}
)

// Add your custom methods and functionality below.
