// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yunloli/aiferry/internal/dao/internal"
)

// modelPriceRulesDao is the data access object for the table model_price_rules.
// You can define custom methods on it to extend its functionality as needed.
type modelPriceRulesDao struct {
	*internal.ModelPriceRulesDao
}

var (
	// ModelPriceRules is a globally accessible object for table model_price_rules operations.
	ModelPriceRules = modelPriceRulesDao{internal.NewModelPriceRulesDao()}
)

// Add your custom methods and functionality below.
