// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yunloli/aiferry/internal/dao/internal"
)

// modelQualityEventsDao is the data access object for the table model_quality_events.
// You can define custom methods on it to extend its functionality as needed.
type modelQualityEventsDao struct {
	*internal.ModelQualityEventsDao
}

var (
	// ModelQualityEvents is a globally accessible object for table model_quality_events operations.
	ModelQualityEvents = modelQualityEventsDao{internal.NewModelQualityEventsDao()}
)

// Add your custom methods and functionality below.
