// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yunloli/aiferry/internal/dao/internal"
)

// priceSourcesDao is the data access object for the table price_sources.
// You can define custom methods on it to extend its functionality as needed.
type priceSourcesDao struct {
	*internal.PriceSourcesDao
}

var (
	// PriceSources is a globally accessible object for table price_sources operations.
	PriceSources = priceSourcesDao{internal.NewPriceSourcesDao()}
)

// Add your custom methods and functionality below.
