// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yunloli/aiferry/internal/dao/internal"
)

// redemptionCodesDao is the data access object for the table redemption_codes.
// You can define custom methods on it to extend its functionality as needed.
type redemptionCodesDao struct {
	*internal.RedemptionCodesDao
}

var (
	// RedemptionCodes is a globally accessible object for table redemption_codes operations.
	RedemptionCodes = redemptionCodesDao{internal.NewRedemptionCodesDao()}
)

// Add your custom methods and functionality below.
