// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yunloli/aiferry/internal/dao/internal"
)

// usageLogsDao is the data access object for the table usage_logs.
// You can define custom methods on it to extend its functionality as needed.
type usageLogsDao struct {
	*internal.UsageLogsDao
}

var (
	// UsageLogs is a globally accessible object for table usage_logs operations.
	UsageLogs = usageLogsDao{internal.NewUsageLogsDao()}
)

// Add your custom methods and functionality below.
